parameters:
    contao_file_usage.file_usage_cache_dir: '%kernel.project_dir%/var'

services:
    _defaults:
        autoconfigure: true

    contao_file_usage.file_usage_cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        public: true
        arguments: ['fileusage', 0, '%contao_file_usage.file_usage_cache_dir%']

    contao_file_usage.query_cache:
        class: Doctrine\DBAL\Cache\QueryCacheProfile
        arguments: [0, 'fileusage']

    contao_file_usage.finder.file_usage:
        class: InspiredMinds\ContaoFileUsage\Finder\FileUsageFinder
        public: true
        arguments:
            - '@contao_file_usage.file_usage_cache'
            - !tagged_iterator { tag: contao_file_usage.provider }
            - '@database_connection'

    contao_file_usage.console.file_usage_warmup:
        class: InspiredMinds\ContaoFileUsage\Console\FileUsageWarmupCommand
        arguments:
            - '@contao_file_usage.finder.file_usage'
            - '@?debug.stopwatch'

    InspiredMinds\ContaoFileUsage\Controller\ReplaceFileReferencesController:
        arguments:
            - '@twig'
            - '@contao.framework'
            - '@translator'
            - '@router'
            - '@contao_file_usage.finder.file_usage'
            - '@contao_file_usage.replace.file_reference'
            - '@contao_file_usage.file_usage_cache'
            - '@contao_file_usage.result.result_enhancer'
            - '@security.helper'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'
        tags: ['controller.service_arguments']

    InspiredMinds\ContaoFileUsage\Controller\ShowFileReferencesController:
        arguments:
            - '@twig'
            - '@contao.framework'
            - '@contao_file_usage.file_usage_cache'
            - '@contao_file_usage.finder.file_usage'
            - '@contao_file_usage.result.result_enhancer'
            - '@security.helper'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'
        tags: ['controller.service_arguments']

    contao_file_usage.cron.build_cache:
        class: InspiredMinds\ContaoFileUsage\Cron\BuildCacheCronJob
        arguments:
            - '@contao_file_usage.finder.file_usage'

    contao_file_usage.event_listener.backend_menu:
        class: InspiredMinds\ContaoFileUsage\EventListener\BackendMenuListener
        arguments:
            - '@request_stack'
        tags: ['kernel.event_listener']

    contao_file_usage.event_listener.data_container.files_permissions:
        class: InspiredMinds\ContaoFileUsage\EventListener\DataContainer\FilesPermissionsCallback
        arguments:
            - '@security.helper'
            - '@request_stack'
        tags:
            - { name: contao.callback, table: tl_files, target: config.onload }

    contao_file_usage.event_listener.data_container.show_references_button:
        class: InspiredMinds\ContaoFileUsage\EventListener\DataContainer\ShowReferencesButtonCallback
        arguments:
            - '@router'
            - '@contao_file_usage.file_usage_cache'
            - '@translator'
            - '@security.helper'
            - '@request_stack'
        tags:
            - { name: contao.callback, table: tl_files, target: list.operations.fileusage.button }

    contao_file_usage.maintenance.clear_file_usage_cache:
        class: InspiredMinds\ContaoFileUsage\Maintenance\ClearFileUsageCache
        public: true
        arguments:
            - '@contao_file_usage.file_usage_cache'

    contao_file_usage.migration.cache_dir:
        class: InspiredMinds\ContaoFileUsage\Migration\CacheDirMigration
        arguments:
            - '@filesystem'
            - '%kernel.environment%'
            - '%kernel.cache_dir%'
            - '%contao_file_usage.file_usage_cache_dir%'

    contao_file_usage.provider.database:
        class: InspiredMinds\ContaoFileUsage\Provider\DatabaseProvider
        arguments:
            - '@database_connection'
            - '@contao.resource_finder'
            - '@contao.framework'

    contao_file_usage.provider.rocksolid_custom_elements:
        class: InspiredMinds\ContaoFileUsage\Provider\RocksolidCustomElementsProvider
        arguments:
            - '@database_connection'

    contao_file_usage.replace.file_reference:
        class: InspiredMinds\ContaoFileUsage\Replace\FileReferenceReplacer
        arguments:
            - '@database_connection'
            - '@contao.framework'

    contao_file_usage.result.result_enhancer:
        class: InspiredMinds\ContaoFileUsage\Result\ResultEnhancer
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@router'
            - '@request_stack'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'

    contao_file_usage.twig.extension:
        class: InspiredMinds\ContaoFileUsage\Twig\Extension
        arguments:
            - '@request_stack'
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
        tags: ['twig.extension']

    InspiredMinds\ContaoFileUsage\Finder\FileUsageFinderInterface: '@contao_file_usage.finder.file_usage'
    InspiredMinds\ContaoFileUsage\Replace\FileReferenceReplacerInterface: '@contao_file_usage.replace.file_reference'
    InspiredMinds\ContaoFileUsage\Result\ResultEnhancerInterface: '@contao_file_usage.result.result_enhancer'
